language: cpp

compiler:
  - clang

sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libsdl2-dev libsdl2_image-dev libsdl2_mixer-dev libsdl2_ttf-dev
  - mkdir bin

script:
  - make
