language: cpp

compiler: clang

sudo: true

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test


before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
  - sudo apt-get install libsdl2-image-dev
  - sudo apt-get install libsdl2-mixer-dev
  - sudo apt-get install libsdl2-ttf-dev
  - mkdir bin

script:
  - make
