language: cpp

sudo: required

dist: precise

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - zoogie/sdl2-snapshots
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
          env: COMPILER=clang++-3.7


before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
  - sudo apt-get install -y libsdl2-image-dev
  - sudo apt-get install -y libsdl2-mixer-dev
  - sudo apt-get install -y libsdl2-ttf-dev

script:
  - mkdir bin
  - make
