language: cpp

sudo: required

dist: precise

branches:
  only: travis_testing

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
          env: COMPILER=clang++-3.8

before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
  - sudo apt-get install -y libsdl2-image-dev
  - sudo apt-get install -y libsdl2-mixer-dev
  - sudo apt-get install -y libsdl2-ttf-dev

script:
  - mkdir bin
  - make
